[theme]
base = "light"
primaryColor = "#f18f01"
font = "serif"

[ui]
hideTopBar = true

[browser]
gatherUsageStats = false

[server]
# browser.gatherUsageStats = false
enableCORS = false           # Disable CORS since the proxy handles it
enableXsrfProtection = false # Secure requests if needed
baseUrlPath = ""             # Adjust this if the app is served under a subpath

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 200

# Enables support for websocket compression.
# Default: false
enableWebsocketCompression = false
